title: Atty. NODA Hayato J.D.
description: >-
  by Atty.NODA Hayato J.D. - Lawyer admitted in Japan / 弁護士　野田隼人（滋賀弁護士会）
twitter_username: nodahayato
github_username: nodahayato

lang: ja

theme: minima
